# Generated by Django 4.1.6 on 2023-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя персонажа')),
                ('characterDesc', models.TextField(null=True, verbose_name='Инфо')),
                ('characterAge', models.IntegerField(null=True, verbose_name='Возраст')),
                ('characteImage', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postContent',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
