# Generated by Django 4.1.6 on 2023-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_character_post_postimage_alter_post_postcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.TextField(null=True, verbose_name='Картинка'),
        ),
    ]
