# Generated by Django 4.1.6 on 2023-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='characteImage',
            field=models.TextField(null=True, verbose_name='Картинка'),
        ),
    ]
